GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjgxODkyNjA2LCJleHAiOjE2ODE4OTI2MjF9.-6WxfcrBCrk1xP19h1FDIjdb31pXgNgKKuEoaECczU8

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": 
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjgxODkyNTg4fQ.jL4wCncAFnmpHkLckyitRHI2BE-uK2ZTrRZ13Qqr7mQ"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}